version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://vw-240-caldeira.duckdns.org"  # Your domain; vaultwarden needs to know it's https to work properly with attachments
      DATABASE_URL: /vw-db/db.sqlite3
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    volumes:
      - vw-data:/data
      - vw-db:/vw-db
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden.entrypoints: websecure
      traefik.http.routers.vaultwarden.tls: true
      traefik.http.routers.vaultwarden.tls.certresolver: production
      traefik.http.routers.vaultwarden.rule: Host(`vw-240-caldeira.duckdns.org`)
      traefik.http.routers.vaultwarden-local.entrypoints: websecure
      traefik.http.routers.vaultwarden-local.tls: true
      traefik.http.routers.vaultwarden-local.rule: Host(`vaultwarden.home`) || Host(`vw.home`) || Host(`enderchest.home`)

volumes:
  vw-data:
    name: vw-data
    driver: local
    driver_opts:
      type: nfs
      o: addr=truenas.home,nfsvers=4
      device: :/mnt/bpool/docker_volumes/vaultwarden/vw-data
  vw-db:
    name: vw-db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/docker_volumes/vaultwarden/vw-db

networks:
  traefik:
    external: true
