version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Lisbon
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent:/config
      - media-fs:/media-fs
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2GiB

volumes:
  qbittorrent:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=truenas.home,rw,nfsvers=4,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/mnt/bpool/docker_volumes/qbittorrent"
  media-fs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=truenas.home,rw,nfsvers=4,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/mnt/bpool/media-fs"
