version: "3.7"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    # image: ghcr.io/hotio/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      # - UMASK=002
      - TZ=Europe/Lisbon
    volumes:
      - sonarr:/config
      - media-fs:/media-fs
    ports:
      - 8989:8989
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1GiB

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    # image: ghcr.io/hotio/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      # - UMASK=002
      - TZ=Europe/Lisbon
    volumes:
      - radarr:/config
      - media-fs:/media-fs
    ports:
      - 7878:7878
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1GiB

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    # image: ghcr.io/hotio/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      # - UMASK=002
      - TZ=Europe/Lisbon
    volumes:
      - bazarr:/config
      - media-fs:/media-fs
    ports:
      - 6767:6767
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2GiB

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    # image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      # - UMASK=002
      - TZ=Europe/Lisbon
    volumes:
      - prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1GiB

volumes:
  sonarr:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=truenas.home,rw,nfsvers=4,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/mnt/bpool/docker_volumes/sonarr"

  radarr:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=truenas.home,rw,nfsvers=4,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/mnt/bpool/docker_volumes/radarr"

  bazarr:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=truenas.home,rw,nfsvers=4,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/mnt/bpool/docker_volumes/bazarr"

  prowlarr:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=truenas.home,rw,nfsvers=4,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/mnt/bpool/docker_volumes/prowlarr"

  media-fs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=truenas.home,rw,nfsvers=4,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/mnt/bpool/media-fs"
