services:
  traefik:
    image: traefik:2.10.4
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # - 8080:8080
    volumes:
      - traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    restart: always
    # environment:
    #   TRAEFIK_GLOBAL_CHECKNEWVERSION: false
    #   TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE: false
    #   TRAEFIK_LOG: true
    #   TRAEFIK_LOG_FILEPATH: /etc/traefik/traefik.log
    #   # TRAEFIK_LOG_FORMAT: json
    #   TRAEFIK_LOG_LEVEL: DEBUG
    #   TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: :80
    #   TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: :443
    #   # TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_CERTRESOLVER: staging
    #   # TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_DOMAINS_n_MAIN: 240-caldeira.duckdns.org
    #   TRAEFIK_API_DASHBOARD: true
    #   TRAEFIK_API_INSECURE: true
    #   TRAEFIK_PROVIDERS_DOCKER: true
    #   TRAEFIK_PROVIDERS_DOCKER_WATCH: true
    #   TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: false
    #   TRAEFIK_PROVIDERS_FILE_DIRECTORY: /etc/traefik/dynamic_config
    #   TRAEFIK_PROVIDERS_FILE_WATCH: true
    #   TRAEFIK_CERTIFICATESRESOLVERS_STAGING: true
    #   TRAEFIK_CERTIFICATESRESOLVERS_STAGING_ACME_CASERVER: https://acme-staging-v02.api.letsencrypt.org/directory
    #   TRAEFIK_CERTIFICATESRESOLVERS_STAGING_ACME_EMAIL: joaocaldeira379@gmail.com
    #   TRAEFIK_CERTIFICATESRESOLVERS_STAGING_ACME_STORAGE: /etc/traefik/acme/acme.json
    #   TRAEFIK_CERTIFICATESRESOLVERS_STAGING_ACME_TLSCHALLENGE: true
    #   TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION: true
    #   TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION_ACME_EMAIL: joaocaldeira379@gmail.com
    #   TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION_ACME_STORAGE: /etc/traefik/acme/acme.json
    #   TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION_ACME_TLSCHALLENGE: true
    #   TRAEFIK_SERVERSTRANSPORT_INSECURESKIPVERIFY: true
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`traefik.home`)
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: basic-auth-global@file

volumes:
  traefik:
    name: traefik
    driver: local
    driver_opts:
      type: nfs
      o: addr=truenas.home,nfsvers=4
      device: :/mnt/bpool/docker_volumes/traefik

networks:
  traefik:
    name: traefik
    driver: bridge
